\hypertarget{classoomph_1_1OomphLibException}{}\section{oomph\+:\+:Oomph\+Lib\+Exception Class Reference}
\label{classoomph_1_1OomphLibException}\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}


{\ttfamily \#include $<$oomph\+\_\+definitions.\+h$>$}

Inheritance diagram for oomph\+:\+:Oomph\+Lib\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=3.000000cm]{classoomph_1_1OomphLibException}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
void \hyperlink{classoomph_1_1OomphLibException_a92da7bc6b484044587ca2e8db4e1e507}{disable\+\_\+error\+\_\+message} ()
\begin{DoxyCompactList}\small\item\em Suppress issueing of the error message in destructor (useful if error is caught successfully!) \end{DoxyCompactList}\end{DoxyCompactItemize}
\subsection*{Protected Member Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{classoomph_1_1OomphLibException_a2bcc47316fcc96608e79bec5ab49f82b}{Oomph\+Lib\+Exception} (const std\+::string \&error\+\_\+description, const std\+::string \&function\+\_\+name, const char $\ast$location, const std\+::string \&exception\+\_\+type, std\+::ostream \&exception\+\_\+stream, const unsigned \&output\+\_\+width, bool list\+\_\+trace\+\_\+back)
\begin{DoxyCompactList}\small\item\em Constructor takes the error description, function name and a location string provided by the O\+O\+M\+P\+H\+\_\+\+E\+X\+C\+E\+P\+T\+I\+O\+N\+\_\+\+L\+O\+C\+A\+T\+I\+ON macro and combines them into a standard header. The exception type will be the string \char`\"{}\+W\+A\+R\+N\+I\+N\+G\char`\"{} or \char`\"{}\+E\+R\+R\+O\+R\char`\"{} and the message is written to the exception\+\_\+stream, with a specified output\+\_\+width. Optionally provide a traceback of the function calls. \end{DoxyCompactList}\item 
\hyperlink{classoomph_1_1OomphLibException_a0cc216d83aa854e965c3c8376d2c4d39}{$\sim$\+Oomph\+Lib\+Exception} ()  throw ()
\begin{DoxyCompactList}\small\item\em The destructor cannot throw an exception (C++ S\+TL standard) \end{DoxyCompactList}\end{DoxyCompactItemize}
\subsection*{Protected Attributes}
\begin{DoxyCompactItemize}
\item 
std\+::ostream $\ast$ \hyperlink{classoomph_1_1OomphLibException_ab9177b3f4d969f3e4d102487165103c7}{Exception\+\_\+stream\+\_\+pt}
\begin{DoxyCompactList}\small\item\em Exception stream to which we write message in destructor. \end{DoxyCompactList}\item 
std\+::stringstream $\ast$ \hyperlink{classoomph_1_1OomphLibException_a94df333a8bdcb4b89eeb516a64a3429e}{Exception\+\_\+stringstream\+\_\+pt}
\begin{DoxyCompactList}\small\item\em String stream that records the error message. \end{DoxyCompactList}\item 
bool \hyperlink{classoomph_1_1OomphLibException_ac374cd3358bf26639860a6778779786d}{Suppress\+\_\+error\+\_\+message}
\begin{DoxyCompactList}\small\item\em Boolean to suppress issuing of the error message in destructor (useful if error is caught successfully!) \end{DoxyCompactList}\end{DoxyCompactItemize}


\subsection{Detailed Description}
===================================================================== A Base class for oomph-\/lib run-\/time exception (error and warning) handling.

The class can only be instantiated by the derived classes \hyperlink{classoomph_1_1OomphLibError}{Oomph\+Lib\+Error} and \hyperlink{classoomph_1_1OomphLibWarning}{Oomph\+Lib\+Warning}. The (protected) constructor combines its string arguments into a standard format for uniform exception reports which are written to the specified output stream. 

Definition at line 173 of file oomph\+\_\+definitions.\+h.



\subsection{Constructor \& Destructor Documentation}
\mbox{\Hypertarget{classoomph_1_1OomphLibException_a2bcc47316fcc96608e79bec5ab49f82b}\label{classoomph_1_1OomphLibException_a2bcc47316fcc96608e79bec5ab49f82b}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!Oomph\+Lib\+Exception@{Oomph\+Lib\+Exception}}
\index{Oomph\+Lib\+Exception@{Oomph\+Lib\+Exception}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{Oomph\+Lib\+Exception()}{OomphLibException()}}
{\footnotesize\ttfamily oomph\+::\+Oomph\+Lib\+Exception\+::\+Oomph\+Lib\+Exception (\begin{DoxyParamCaption}\item[{const std\+::string \&}]{error\+\_\+description,  }\item[{const std\+::string \&}]{function\+\_\+name,  }\item[{const char $\ast$}]{location,  }\item[{const std\+::string \&}]{exception\+\_\+type,  }\item[{std\+::ostream \&}]{exception\+\_\+stream,  }\item[{const unsigned \&}]{output\+\_\+width,  }\item[{bool}]{list\+\_\+trace\+\_\+back }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [protected]}}



Constructor takes the error description, function name and a location string provided by the O\+O\+M\+P\+H\+\_\+\+E\+X\+C\+E\+P\+T\+I\+O\+N\+\_\+\+L\+O\+C\+A\+T\+I\+ON macro and combines them into a standard header. The exception type will be the string \char`\"{}\+W\+A\+R\+N\+I\+N\+G\char`\"{} or \char`\"{}\+E\+R\+R\+O\+R\char`\"{} and the message is written to the exception\+\_\+stream, with a specified output\+\_\+width. Optionally provide a traceback of the function calls. 

The \hyperlink{classoomph_1_1OomphLibException}{Oomph\+Lib\+Exception} constructor takes the error description, function name, a location string provided by the O\+O\+M\+P\+H\+\_\+\+E\+X\+C\+E\+P\+T\+I\+O\+N\+\_\+\+L\+O\+C\+A\+T\+I\+ON and an exception type \char`\"{}\+W\+A\+R\+N\+I\+N\+G\char`\"{} or \char`\"{}\+E\+R\+R\+O\+R\char`\"{} and combines them into a standard error message that is written to the exception stream. The output\+\_\+width of the message can also be specified. Optionally provide a traceback of the function calls. 

Definition at line 139 of file oomph\+\_\+definitions.\+cc.



References Exception\+\_\+stream\+\_\+pt, Exception\+\_\+stringstream\+\_\+pt, i, oomph\+::\+Oomph\+Lib\+Error\+::\+Output\+\_\+width, oomph\+::\+Oomph\+Lib\+Warning\+::\+Output\+\_\+width, print\+\_\+stacktrace(), oomph\+::\+Oomph\+Lib\+Error\+::\+Stream\+\_\+pt, oomph\+::\+Oomph\+Lib\+Warning\+::\+Stream\+\_\+pt, oomph\+::\+Global\+\_\+string\+\_\+for\+\_\+annotation\+::string(), and Suppress\+\_\+error\+\_\+message.

\mbox{\Hypertarget{classoomph_1_1OomphLibException_a0cc216d83aa854e965c3c8376d2c4d39}\label{classoomph_1_1OomphLibException_a0cc216d83aa854e965c3c8376d2c4d39}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!````~Oomph\+Lib\+Exception@{$\sim$\+Oomph\+Lib\+Exception}}
\index{````~Oomph\+Lib\+Exception@{$\sim$\+Oomph\+Lib\+Exception}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{$\sim$\+Oomph\+Lib\+Exception()}{~OomphLibException()}}
{\footnotesize\ttfamily oomph\+::\+Oomph\+Lib\+Exception\+::$\sim$\+Oomph\+Lib\+Exception (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) throw  ) \hspace{0.3cm}{\ttfamily [protected]}}



The destructor cannot throw an exception (C++ S\+TL standard) 

created in the constructor (unless suppresed)

The \hyperlink{classoomph_1_1OomphLibException}{Oomph\+Lib\+Exception} destructor actually spawns the error message 

Definition at line 121 of file oomph\+\_\+definitions.\+cc.



References oomph\+::\+Terminate\+Helper\+::\+Exception\+\_\+stringstream\+\_\+pt.



\subsection{Member Function Documentation}
\mbox{\Hypertarget{classoomph_1_1OomphLibException_a92da7bc6b484044587ca2e8db4e1e507}\label{classoomph_1_1OomphLibException_a92da7bc6b484044587ca2e8db4e1e507}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!disable\+\_\+error\+\_\+message@{disable\+\_\+error\+\_\+message}}
\index{disable\+\_\+error\+\_\+message@{disable\+\_\+error\+\_\+message}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{disable\+\_\+error\+\_\+message()}{disable\_error\_message()}}
{\footnotesize\ttfamily void oomph\+::\+Oomph\+Lib\+Exception\+::disable\+\_\+error\+\_\+message (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}



Suppress issueing of the error message in destructor (useful if error is caught successfully!) 



Definition at line 180 of file oomph\+\_\+definitions.\+h.



References oomph\+::\+Global\+\_\+string\+\_\+for\+\_\+annotation\+::string(), and oomph\+::\+Terminate\+Helper\+::suppress\+\_\+exception\+\_\+error\+\_\+messages().



Referenced by oomph\+::\+Finite\+Element\+::locate\+\_\+zeta().



\subsection{Member Data Documentation}
\mbox{\Hypertarget{classoomph_1_1OomphLibException_ab9177b3f4d969f3e4d102487165103c7}\label{classoomph_1_1OomphLibException_ab9177b3f4d969f3e4d102487165103c7}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!Exception\+\_\+stream\+\_\+pt@{Exception\+\_\+stream\+\_\+pt}}
\index{Exception\+\_\+stream\+\_\+pt@{Exception\+\_\+stream\+\_\+pt}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{Exception\+\_\+stream\+\_\+pt}{Exception\_stream\_pt}}
{\footnotesize\ttfamily std\+::ostream$\ast$ oomph\+::\+Oomph\+Lib\+Exception\+::\+Exception\+\_\+stream\+\_\+pt\hspace{0.3cm}{\ttfamily [protected]}}



Exception stream to which we write message in destructor. 



Definition at line 209 of file oomph\+\_\+definitions.\+h.



Referenced by Oomph\+Lib\+Exception().

\mbox{\Hypertarget{classoomph_1_1OomphLibException_a94df333a8bdcb4b89eeb516a64a3429e}\label{classoomph_1_1OomphLibException_a94df333a8bdcb4b89eeb516a64a3429e}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!Exception\+\_\+stringstream\+\_\+pt@{Exception\+\_\+stringstream\+\_\+pt}}
\index{Exception\+\_\+stringstream\+\_\+pt@{Exception\+\_\+stringstream\+\_\+pt}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{Exception\+\_\+stringstream\+\_\+pt}{Exception\_stringstream\_pt}}
{\footnotesize\ttfamily std\+::stringstream$\ast$ oomph\+::\+Oomph\+Lib\+Exception\+::\+Exception\+\_\+stringstream\+\_\+pt\hspace{0.3cm}{\ttfamily [protected]}}



String stream that records the error message. 



Definition at line 212 of file oomph\+\_\+definitions.\+h.



Referenced by Oomph\+Lib\+Exception().

\mbox{\Hypertarget{classoomph_1_1OomphLibException_ac374cd3358bf26639860a6778779786d}\label{classoomph_1_1OomphLibException_ac374cd3358bf26639860a6778779786d}} 
\index{oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}!Suppress\+\_\+error\+\_\+message@{Suppress\+\_\+error\+\_\+message}}
\index{Suppress\+\_\+error\+\_\+message@{Suppress\+\_\+error\+\_\+message}!oomph\+::\+Oomph\+Lib\+Exception@{oomph\+::\+Oomph\+Lib\+Exception}}
\subsubsection{\texorpdfstring{Suppress\+\_\+error\+\_\+message}{Suppress\_error\_message}}
{\footnotesize\ttfamily bool oomph\+::\+Oomph\+Lib\+Exception\+::\+Suppress\+\_\+error\+\_\+message\hspace{0.3cm}{\ttfamily [protected]}}



Boolean to suppress issuing of the error message in destructor (useful if error is caught successfully!) 



Definition at line 216 of file oomph\+\_\+definitions.\+h.



Referenced by Oomph\+Lib\+Exception().



The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
\hyperlink{oomph__definitions_8h}{oomph\+\_\+definitions.\+h}\item 
\hyperlink{oomph__definitions_8cc}{oomph\+\_\+definitions.\+cc}\end{DoxyCompactItemize}
